### ISSUE TITLE
When using root path '/' the page doesn't render on refresh

### ISSUE THREAD

**Issue by rob-balfre** [TehShrike/abstract-state-router#116]
I'm trying to add a home '/' route to my app (using svelte-state-renderer).  I've used the examples over on [state-router-example ](https://github.com/TehShrike/state-router-example) as a base but when I change the route in login.js from 'login' to '/' or an empty string the page is blank on refresh.

**Comment by TehShrike** [comment]
Is the [`evaluateCurrent`](https://github.com/TehShrike/state-router-example/blob/efa9f57c4bf436c2379d7aa562874699a6e82a8a/implementations/svelte/index.js#L13) line updated?

Is the router emitting a [`routeNotFound`](https://github.com/TehShrike/abstract-state-router#state-change) event?

What is the url when you refresh?  If you wipe out the hash fragment and refresh, does it behave differently?

**Comment by rob-balfre** [comment]
evaluateCurrent is pointing to 'login'.  routeNotFound is not being fired. If I manually remove the hash from the url and refresh it works.

**Comment by rob-balfre** [comment]
It's pretty easy to recreate, just update this [line](https://github.com/TehShrike/state-router-example/blob/efa9f57c4bf436c2379d7aa562874699a6e82a8a/implementations/svelte/login/login.js#L7) to point to '/'

**Comment by TehShrike** [comment]
And load what url?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by TehShrike** [comment]
mm, I was able to reproduce.  It looks like `evaluateCurrentRoute` doesn't have any effect when the url is `/` and the default state that you're giving it has a route of `/`.  No events fired or anything.  I'll make a unit test.

**Comment by TehShrike** [comment]
It's a bug in hash-brown-router :-o

**Comment by TehShrike** [comment]
Published as 6.0.4.

**Comment by TehShrike** [comment]
I confirmed that it works with that change to `login`'s route in state-router-example.

Thanks for reporting! 👍

**Comment by rob-balfre** [comment]
@TehShrike awesome thanks
