### ISSUE TITLE
No code examples in the readme

### ISSUE THREAD

**Issue by ArtskydJ** [TehShrike/abstract-state-router#22]
It's hard to figure out w/o code examples, imo.

**Comment by TehShrike** [comment]
I agree.  Want to write some up?  I'm going to flesh out [state-router-example](https://github.com/TehShrike/state-router-example) some more, but that's going to be as much a demo of different rendering tools as anything.

For the readme here, a couple addState calls, a go call, and an evaluateCurrentRoute call for people to copy/paste into their own code to start from should be enough.
