### ISSUE TITLE
Curious bug here - Navigating between the same route does not cause reactivation

### ISSUE THREAD

**Issue by osiloke** [TehShrike/abstract-state-router#36]
Great initiative but i noticed a bug. 
I have a route `route: '/:entity/new'`
When i navigate to `/one_entity/new`, the associated state is activated and rendered.
Then i navigate to `/another_entity/new`, the associated state is not reactivated since its the same route.
Hence the view (riot tag in my case) does not get updated.

**Comment by osiloke** [comment]
Oops, not a bug, just ignorance. I wasn't updating whatever i was doing

**Comment by TehShrike** [comment]
Whew! :-) On the positive side, that did get me to write another test out of paranoia.

**Comment by osiloke** [comment]
sorry about that, but that was some grade A, super response! :+1:
