### ISSUE TITLE
Are there any plans for html5 type url's i.e no hash in url

### ISSUE THREAD

**Issue by osiloke** [TehShrike/abstract-state-router#39]

**Comment by TehShrike** [comment]
**Short answer**: I am not planning on it, but I would entertain discussion/pull requests.

**Long answer**: When you use pushState exclusively, you have to be able to serve up static content from your server.  If you're at `/mysite/app/account/profile` and you `window.pushState({}, 'My app', '/mysite/app/account/email')`, you have to be able to display that same content when the user tries to refresh that page.  Either by

1. be able to serve up the correct static content from the server (requiring you to be running the abstract-state-router on the server-side)
2. on the server-side, for *all* requests with routes matching `/mysite/*`, serve up the same index.html file

I'm not personally interested in either of those, the difficulty of the first one and the janketiness of the second put me off a bit.

I understand that other people may like one of those options though, and I'm not against that functionality being added to the abstract-state-router, as long as there were good tests and it didn't raise the complexity of the code much.

As far as I know it would probably take

- making a pushState version of [hash-brown-router](https://github.com/TehShrike/hash-brown-router)
- fixing [this one line where hashes are currently always added to paths](https://github.com/TehShrike/abstract-state-router/blob/master/index.js#L252)

**Comment by osiloke** [comment]
These are valid points. I'm evaluating riotjs as an alternative to angular for the rewrite of a web app, and i needed push state url's because my server pretty much does option2. 
If i have some time i will create a PR, at least as an option.

**Comment by TehShrike** [comment]
Building a router to the hash-brown-router interface based on the [history](https://www.npmjs.com/package/history) module might be a good idea.

**Comment by TehShrike** [comment]
I've become a bit more motivated to support this myself  Did you ever get a chance to experiment with it @osiloke ?  Otherwise I may try it myself.

**Comment by osiloke** [comment]
I never actually got around to doing this, i ended up making a riotjs helper to use with pagejs, sorry

**Comment by TehShrike** [comment]
No worries.  I'll probably start working on this once I have cross-browser testing all set up for hash-brown-router.

**Comment by TehShrike** [comment]
I've got an HTML5 pushState router over here called [sausage-router](https://github.com/TehShrike/sausage-router).  It should plug directly in to the hash-brown-router and work fine with the abstract-state-router, but I'd like to do some more cross-browser testing with Browserstack before I move on to changing abstract-state-router.

**Comment by TehShrike** [comment]
pushState routing should work now that I [allowed for not having the hash in the state paths](https://github.com/TehShrike/abstract-state-router/commit/b30da1f2062439b772589c7c5b43e4b4063bca85), and updated the readme to have a [section on HTML5/pushState](https://github.com/TehShrike/abstract-state-router#html5pushstate-routing).

I don't consider it usable for my own apps for the reasons mentioned above in this thread, and now in that section of the readme, but HTML5/pushState routing is now technically supported.

**Comment by TehShrike** [comment]
Related: https://github.com/TehShrike/abstract-state-router/issues/48
