### ISSUE TITLE
defaultChild state with an empty route string is not activated when navigating directly to its parent

### ISSUE THREAD

**Issue by crissdev** [TehShrike/abstract-state-router#40]
The following link if navigated directly displays a blank page. 
http://tehshrike.github.io/state-router-example/implementations/ractive/index.html#/app/topics/

**Comment by TehShrike** [comment]
Hmm.  I wonder if that has anything to do with the route string being empty.  I'll write some tests later

**Comment by crissdev** [comment]
:+1: Man you're fast!

Yeah, setting the route to `none`, for instance, solves it.

**Comment by TehShrike** [comment]
All right, good to know.  I'd like to be able to support empty route strings if possible, so this is a bug I'd like to fix.

[The secret to my speed](https://github.com/ptsochantaris/trailer)

**Comment by TehShrike** [comment]
Finally got that fixed, sorry for the wait.  Thanks for reporting the issue!

**Comment by TehShrike** [comment]
There were still unfixed edge cases!  I added more tests and fixed code in https://github.com/TehShrike/abstract-state-router/commit/85112c7965c1bcdea1576b9d8c4f7585b65380e4
