### ISSUE TITLE
Replace extend with xtend

### ISSUE THREAD

**Issue by TehShrike** [TehShrike/abstract-state-router#43]
[xtend](http://npm.im/xtend) is smaller and better, and overlaps with hash-brown-router.

**Comment by crissdev** [comment]
Not quite possible because [this object](https://github.com/TehShrike/abstract-state-router/blob/v5.7.0/index.js#L208) needs methods from `EventEmitter` which are not copied by `xtend`. Thoughts?

----
FYI, it works with `Object.assign` but that requires `node >= v4.0.0`.

**Comment by TehShrike** [comment]
hmm.

Maybe using `require('xtend/mutable')` would be the best short-term improvement.  It looks like it works similarly to `extend`.

**Comment by crissdev** [comment]
Yeah, that should work.

**Comment by ArtskydJ** [comment]
```js
var emitter = new EventEmitter()
var context = Object.create(emitter)
extend(context, {
	domApi: activeDomApis[state.name],
	data: state.data,
	parameters: parameters,
	content: getContentObject(activeStateResolveContent, state.name)
})
activeEmitters[state.name] = emitter
```
could turn into
```js
var emitter = new EventEmitter()
var context = Object.create(emitter)

context.domApi = activeDomApis[state.name],
context.data = state.data,
context.parameters = parameters,
context.content = getContentObject(activeStateResolveContent, state.name)

activeEmitters[state.name] = emitter
```

But I don't think it's a big deal.

**Comment by divmgl** [comment]
I agree with @ArtskydJ. Unless you're using it somewhere else, doesn't really make sense to include it.
