### ISSUE TITLE
defaultRouterOptions is not exported properly

### ISSUE THREAD

**Issue by lucianapreda** [TehShrike/abstract-state-router#65]
I've found this solution to fix the problem:
in default-router-options.js:
var  defaultRouterOptions = module.exports = { "reverse":true}
instead of:
{ "reverse":true}

**Comment by TehShrike** [comment]
node/browserify will parse `.json` files as JSON if you `require()` them: https://nodejs.org/dist/latest-v4.x/docs/api/modules.html

The tests are currently passing: https://travis-ci.org/TehShrike/abstract-state-router

Are you using a different bundler?  What's the symptom you ran into?

**Comment by AgentChris** [comment]
I have the same problem and I am using webpack

**Comment by ArtskydJ** [comment]
Webpack is unable to load json files via `require`, if I remember right.

@TehShrike A possible workaround would be to make that .json file into a .js file...

**Comment by TehShrike** [comment]
Patch published as 5.12.2.

Would anyone be willing to open a pull request adding a new test file that attempts a build with Webpack to prevent any future issues with the Webpack build?
