### ISSUE TITLE
URLs with multiple routes associated are not deterministic

### ISSUE THREAD

**Issue by ArtskydJ** [TehShrike/abstract-state-router#75]
Get all the files in [this gist](https://gist.github.com/ArtskydJ/e16bfaea4febcea197f853f2a802ba81)
Host them on localhost
Browse to asr-bug.html
Change the hash to #/room/new
...Note that you see room/new
Refresh the page
...Note that you see room/:room

Expected behavior:
URLs should be deterministic, and always send you to the same state

**Comment by ArtskydJ** [comment]
I think I was using 5.12.4 (latest)

**Comment by TehShrike** [comment]
Fixed in hash-brown-router 1.5.3 https://github.com/TehShrike/hash-brown-router/issues/8
