### ISSUE TITLE
State name should be optional to `state.go`

### ISSUE THREAD

**Issue by TehShrike** [TehShrike/abstract-state-router#83]
If the first argument to `state.go` is not a string, then it should behave as if you had passed in the name of the current state.

**Discussion point**: should the "current state" be the last state that the router started transitioning to, or should it be the last state that was fully loaded?

Put another way, if you call `redirect({ someParameter: 'some other option' })` inside a `resolve` function, should it redirect you to the state that was in the middle of being loaded, or the state before that?

I'm leaning towards the state that you're in the middle of transitioning to, but I'm open to other arguments.

**Comment by daytonlowell** [comment]
I've created 3 failing tests for this in [my branch]( https://github.com/daytonlowell/abstract-state-router)

The last one, 'calling redirect with no stateName in resolve should use current state', has an issue where the 'second' state never gets called.

**Comment by TehShrike** [comment]
The tests should be good now (I added route strings).  I pushed them up to https://github.com/TehShrike/abstract-state-router/tree/83-null-state-name-passed-to-go-function

**Comment by TehShrike** [comment]
I think that the "current state" should be the one that you're transitioning to.  That way if you pass in `null` to the redirect function inside a `resolve`, you will be going to that same state instead of the state before.

This behavior is checked by the third test @daytonlowell wrote, so as soon as those new tests are passing and the docs are updated then the feature should be good to go.

**Comment by TehShrike** [comment]
Published as 5.13.0
