### ISSUE TITLE
Modern JS features

### ISSUE THREAD

**Issue by TehShrike** [TehShrike/abstract-state-router#89]
Right now abstract-state-router doesn't require any transforms (beyond CommonJS module resolution) to run in an ES5 environment.

ES2015 spreads and spreads, and at this point I feel like most people using abstract-state-router are probably already transpiling to ES5 if they want to support IE11 or older.  Certainly anyone using Webpack is, and anyone using Browserify would continue having no problem, as long as the appropriate transforms were added to the package.json.

What could/should be done during such an upgrade?  Things that come to mind are
1. drop the Promise polyfill
2. upgrade to new language features like `const` and arrow functions and object destructuring
3. ~~change the `resolve` function to take an arguments object instead of two ordered arguments before the callback (probably should have been that way already)~~
4. ~~support promises more explicitly?~~ I'm not sure if anything there's actually anything left to do to make the library fully Promise-friendly

**Comment by TehShrike** [comment]
It would be a good idea to resolve #86 before this.

**Comment by saibotsivad** [comment]
You could take a proverbial page from a solid project like [moment.js](http://momentjs.com/) and write everything in ECMAScript6, but still provide a transpiled ECMAScript5 JS file to maintain backwards compatibility/be friendly.

Copied from their [README file](https://github.com/moment/moment/blob/develop/README.md#port-to-ecmascript-6-version-2100):

> Moment 2.10.0 does not bring any new features, but the code is now written in
> ECMAScript 6 modules and placed inside `src/`. Previously `moment.js`, `locale/*.js` and
> `test/moment/*.js`, `test/locale/*.js` contained the source of the project. Now
> the source is in `src/`, temporary build (ECMAScript 5) files are placed under
> `build/umd/` (for running tests during development), and the `moment.js` and
> `locale/*.js` files are updated only on release.

If you think about going this route, I suggest looking at how they structured their files. You probably wouldn't need that much complexity, but they really do try to handle lots of edge cases, so it's a useful exercise.

**Comment by TehShrike** [comment]
That's a valid path, but moment.js is different from abstract-state-router in that it has always aimed to support the "download a single file and include it with a `<script>` tag" crowd, and abstract-state-router has always only aimed to serve the CommonJS-transpiling crowd.

Narrowing my audience like this makes me feel all right about using modern features with a `browser` property in the package.json for browserify, while assuming that the Webpack folks already have ES6->ES5 transpiling turned on if they care about supporting ES5.

It would be nice to [maintain wzrd.in support via transforms](https://github.com/jfhbrook/wzrd.in/issues/43), though.

**Comment by TehShrike** [comment]
I've updated the current post based on my current thought process.

Modernizing the internal code and dropping the Promise polyfill doesn't mean that the interface needs to change, or that I need to stop shipping ES5 code.

Any breaking changes will be pushed off into [some-day eventually dream-land](https://github.com/TehShrike/abstract-state-router/wiki) (which will still hopefully not be too disruptive).

**Comment by TehShrike** [comment]
This was fixed in #115
